services:
  ewm-service:
    build: ewm-service
    image: ewm-service-image
    container_name: ewm-service-container
    ports:
      - "8080:8080"

  ewm-db:
    image: postgres:16.1

  stats:
    build: stats
    image: stats-image
    container_name: stats-container
    ports:
      - "9090:9090"

  stats-db:
    image: postgres:16.1
